<?php
// @codingStandardsIgnoreFile
/**
 * @var \Dibs\EasyCheckout\Block\Checkout $block
 */
?>

<?php if ($block->getUseOverlayIframe() || $block->getUseEmbededVanillaFlow()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "checkoutMode": {
                    "isOverlay": "<?= $block->getUseOverlayIframe() ?>",
                    "isVanillaEmbeded": "<?= $block->getUseEmbededVanillaFlow() ?>"
                }
            }
        }
    </script>
<?php endif; ?>
<?php if ($block->getUseEmbededVanillaFlow()): ?>
    <?php //https://developer.adobe.com/commerce/php/development/security/content-security-policies/#whitelist-an-inline-script-or-style ?>
    <?= $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        "\n
        var script = document.createElement('script');\n
        script.type = 'text/javascript';\n
        script.src = '" . $block->getChildBlock('dibs_easy_checkout_script')->getSource() ."';\n
        \n
        document.getElementsByTagName('head')[0].appendChild(script);\n",
        false
    ); ?>
<?php endif; ?>
