<?php
// @codingStandardsIgnoreFile
/**
 * @var \Dibs\EasyCheckout\Block\Checkout $block
 */
?>

<?php if ($block->getUseOverlayIframe() || $block->getUseEmbededVanillaFlow()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "checkoutMode": {
                    "isOverlay": "<?= $block->getUseOverlayIframe() ?>",
                    "isVanillaEmbeded": "<?= $block->getUseEmbededVanillaFlow() ?>"
                }
            }
        }
    </script>
<?php endif; ?>
<?php if ($block->getUseEmbededVanillaFlow()): ?>
    <script>
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = '<?= $block->getChildBlock('dibs_easy_checkout_script')->getSource(); ?>';

        document.getElementsByTagName('head')[0].appendChild(script);
    </script>
<?php endif; ?>
