<div id="dibs-easy-checkout_dibs">
    <div id="dibsOrderJS">
        <?php if ($block->getUseIframe()): ?>
            <script>
                var checkoutOptions = {
                    checkoutKey: "<?php echo $block->getDibsCheckoutKey(); ?>", //[Required] Test or Live GUID with dashes
                    paymentId: "<?php echo $block->getDibsPaymentId(); ?>", //[required] GUID without dashes
                    containerId: "dibsOrderJS",
                    language: "<?php echo $block->getDibsLocale(); ?>",
                };
                var _dibsCheckout = new Dibs.Checkout(checkoutOptions);
            </script>
        <?php endif; ?>
    </div>
</div>
