trigger:
  - main
  - develop

parameters:
  - name: phpVersion
    type: string
    default: 8.1
  - name: ShouldDeployApplication
    type: boolean
    default: false

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: Infra
      type: git
      name: ECOM-EASY-PLUGINS/connect
      ref: refs/heads/feature/run-deploy-after-magento2-module

stages:
  - stage: Validate
    displayName: Validate
    jobs:
      - job: Validate_Code
        steps:
          - template: /pipelines/steps/install-php.yaml@Infra
            parameters:
              phpVersion: ${{ parameters.phpVersion }}
          - script: |
              find ./src -type f -name '*.php' ! -path './src/vendor/*' -print0 \
                | xargs -0 -n 1 php -l | (! grep -Ev '^No syntax errors detected in ')
            displayName: 'PHP Syntax Checker (lint)'
