<?php

use Nexi\Checkout\Block\Info\Nexi;

/** @var $block Nexi */
/** @var $escaper \Magento\Framework\Escaper */
?>

<?= $block->getChildHtml() ?>
<table class="admin__table-secondary order-information-table">
    <tbody>
        <tr>
            <th><?= $escaper->escapeHtml(__('Payment Provider')) ?></th>
            <td><img alt="Nexi Logo" style="width: 45px; height: 15px; background-color: white; "
                     src="<?= $escaper->escapeHtml($block->getLogo() ? $block->getLogo() : ''); ?>"/></td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Payment Method')) ?></th>
            <td><?= $escaper->escapeHtml(
                $block->getSelectedPaymentMethodData()[Nexi::SELECTED_PATMENT_METHOD] ?? ''
            ) ?></td>
        </tr>
        <tr>
            <th><?= $escaper->escapeHtml(__('Payment Type')) ?></th>
            <td><?= $escaper->escapeHtml(
                $block->getSelectedPaymentMethodData()[Nexi::SELECTED_PATMENT_TYPE] ?? ''
            ) ?></td>
        </tr>
    </tbody>
</table>
