<?php

/**
 * Dibs Order comments template
 */
?>
<div id="dibs-easy-checkout_comment" class="dibs-easy-checkout-block comment">
    <?php $customerComment = $block->getQuote()->getCustomerNote(); ?>
    <form method="post" action="<?php echo $block->getCommentSubmitUrl(); ?>" id="dibs-comment">
        <div class="fieldset comment">
            <div class="input-box field">
                <textarea value="" placeholder="<?php echo __('Enter a comment for this order'); ?>"
                          name="dibs_customer_comment" id="dibs_order_comment_textarea"
                          class="dibs-easy-checkout-show-on-focus input-text"><?php echo $customerComment; ?></textarea>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button id="dibsCommentSubmit" type="submit" title="<?php echo __('Save'); ?>"
                            class="action apply dibs-primary btn-dibs"><?php echo __('Save'); ?></button>
                </div>
            </div>
        </div>
    </form>
</div>