<?php
// @codingStandardsIgnoreFile

$cartHelper = $this->helper('Dibs\EasyCheckout\Helper\Cart');
$allowedCountries = $cartHelper->getAllowedCountriesNames();

?>
<div class="dibs-easy-checkout-shipping dibs-easy-checkout-section mobile-show"
     id="dibs-easy-checkout-shipping">
    <div class="dibs-easy-checkout-title" data-role="title">
        <h4 id="dibs-easy-checkout-review-heading" role="heading" aria-level="2">
            <?php echo $block->escapeHtml(__('Shipping Method')) ?>
        </h4>
    </div>
    <div class="dibs-easy-checkout-section-content" data-role="content"
         aria-labelledby="dibs-easy-checkout-review-heading">
        <form method="post" id="shipping-method-form"
              action="<?php echo $block->escapeUrl($block->getShippingMethodUrl()); ?>"
              class="form">
            <select class="country" id="country-box">
                <option><?= __('Country') ?></option>
                <?php foreach ($allowedCountries as $key => $country): ?>
                    <option data-title="<?= $country ?>" value="<?= $key ?>"><?= $country ?></option>
                <?php endforeach; ?>
            </select>
            <input class="postcode" type="text" id="postcode-box" name="postal"
                   placeholder="<?php echo __('Postal code') ?>"/>
            <button id="dibs-easy-checkout-set-postcode-button"
                    class="action dibs-primary" title="<?php echo __('Choose Delivery'); ?>">
                <span><?php echo __('Choose Delivery'); ?></span>
            </button>
            <?php echo $block->getChildHtml('shipping_method'); ?>
        </form>
        <?php if ($addrUrl = $block->getShippingAddressSubmitUrl()): ?>
            <?php echo $block->getChildHtml('shipping_address'); ?>
        <?php endif; ?>
    </div>
</div>

