<?php
// @codingStandardsIgnoreFile
$subscribe = $block->subscribeNewsletter();

?>
<div id="dibs-easy-checkout_newsletter" class="dibs-easy-checkout-block dibs-easy-checkout-block-discount">
    <?php $customerComment = $block->getQuote()->getCustomerNote(); ?>
    <form method="post" action="<?php echo $block->getNewsletterSubmitUrl(); ?>" id="dibs-easy-checkout-newsletter-form">
        <div class="fieldset comment">
                <input type="checkbox" name="newsletter" value="1" <?php echo $subscribe?'checked="checked"':'';?> id="newsletter" title="<?php echo __('Sign Up for Our Newsletter') ?>" class="checkbox"   />
                <label for="newsletter"><span class="tick"></span> <?php echo __('Sign Up for Our Newsletter') ?></label>
        </div>
    </form>
</div>