<?php
// @codingStandardsIgnoreFile

$quote = $block->getQuote();
$shippingAddress = $quote->getShippingAddress();
$cartHelper = $this->helper('Dibs\EasyCheckout\Helper\Cart');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
/** @var Magento\Framework\Pricing\Helper\Data $priceHelper */

$widgetHelper = $this->helper(\Dibs\EasyCheckout\Helper\EasycheckoutUdc::class);
if ($widgetHelper->isShippingBlockReplaced()) {
    return;
}

?>
<span class="shipping-price" id="dibs-easy-checkout_dibs_shipping_total">
    <?= ($shippingAddress === null || $shippingAddress->getShippingInclTax() === null ) ? __('_') : $priceHelper->currency($shippingAddress->getShippingInclTax()) ?>
</span>
