<div class="dibs_information"></div>
<div id="rh-custom-popup-modal">
    
</div>
<?php
//https://magento.stackexchange.com/questions/158541/magento-2-how-to-send-data-using-ajax-form-in-custom-form
?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Notification',
                id : 'title_page',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            $.ajax({
                url: "<?php  echo $block->getUrl('grid/reporting'); ?>",
                type: 'GET',
                dataType: 'json',
                complete: function(response)
                {        
                    var responseData = response.responseJSON;
                    if (responseData.status == '00' || responseData.status == '11') {
                        var messageData = $.parseJSON(responseData.message);
                        
                        var popup = modal(options, $('#rh-custom-popup-modal'));
                        $('#rh-custom-popup-modal').modal('openModal');
                        var textData = '<div class="modal-body">';
                        if(responseData.status == '00') {
                            textData += '<h4 class="modal-title">'+ messageData.notification_message +'</h4>';
                            textData += '<div class="form-group-lg">';
                            textData += '<label class="form-control-label">Latest Plugin Version : </label> ' + messageData.plugin_version + ' version </br>';
                            textData += '<label class="form-control-label">Shop Version Compatible : </label> ' + messageData.shop_version + '</br>';
                            if(messageData.repo_links != "") {
                                textData += '<label class="form-control-label">Github Link : </label> <a href="'+ messageData.repo_links +'" target="_blank">Click here</a> </br>';
                            }
                            if(messageData.tech_site_links != "") {
                                textData += '<label class="form-control-label">TechSite Link : </label> <a href="'+ messageData.tech_site_links +'" target="_blank">Click here</a> </br>';
                            }
                            if(messageData.marketplace_links != "") {
                                textData += '<label class="form-control-label">MarketPlace Link : </label> <a href="'+ messageData.marketplace_links +'" target="_blank">Click here</a> </br>';
                            }
                            textData += '</div>';
                        }
                        if(responseData.status == '11') {
                            textData += '<h4 class="modal-title">'+ messageData.notification_message +'</h4>';
                        }
                        $('#rh-custom-popup-modal').html(textData);
                    }
                },
                error: function (xhr, status, errorThrown)
                {
                    console.log(errorThrown);
                }
            });
        }
    );
</script>