<?php
// @codingStandardsIgnoreFile

/** @var $block Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
?>
<tbody class="dibs-easy-checkout-cart dibs-easy-checkout-item">
<tr>
    <td class="dibs-easy-checkout-col item" data-th="<?php echo $block->escapeHtml(__('Product Name'));?>">
        <div class="product-item-details">
          <div class="product-item-image">
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            </div>
            <div class="product-item-info">
            <strong class="product name product-item-name"><?php echo $block->escapeHtml($block->getProductName()) ?></strong>

            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($addtInfoBlock = $block->getProductAdditionalInformationBlock()):?>
                <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>
    <?php if(0): //maybe a future adminhtml switch will control this? ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price'));?>">
		    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceInclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax'));?>">
                    <?php echo $block->getUnitPriceInclTaxHtml($_item); ?>
                </span>
		    <?php endif; ?>
		    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceExclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax'));?>">
                    <?php echo $block->getUnitPriceExclTaxHtml($_item); ?>
                </span>
		    <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="dibs-easy-checkout-col qty" data-th="<?php echo $block->escapeHtml(__('Qty'));?>">
        <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
        ?>
        <div class="qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <span class="remove-product"><i class="fa fa-trash"></i></span>
            <span class="qty">
                <span class="input-number-increment"><i class="fa fa-angle-up"></i></span>
                <span class="input-number-decrement"><i class="fa fa-angle-down"></i></span>
                <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                       name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                       data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                       data-cart-product-id="<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                       data-cart-form-key="<?php echo $FormKey->getFormKey();?>"
                       data-cart-url-submit="<?= /* @escapeNotVerified */ $block->getUrl('checkout/sidebar/updateItemQty') ?>"
                       data-cart-url-update="<?= /* @escapeNotVerified */ $block->getUrl('dibs-easy-checkout/order/cart') ?>"
                       data-cart-url-remove="<?= /* @escapeNotVerified */ $block->getUrl('checkout/sidebar/removeItem'); ?>"
                       value="<?php /* @escapeNotVerified */ echo $_item->getQty() ?>"
                       type="number"
                       min="1"
                       size="4"
                       title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                       class="input-text qty ajax-qty-change"
                       maxlength="12"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
            </span>
        </div>
    </td>

    <td class="dibs-easy-checkout-col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceInclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
            <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax'));?>">
                    <?php echo $block->getRowTotalInclTaxHtml($_item); ?>
                </span>
        <?php endif; ?>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartPriceExclTax() || $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax'));?>">
                    <?php echo $block->getRowTotalExclTaxHtml($_item); ?>
                </span>
        <?php endif; ?>
    </td>
  </div>
</tr>
</tbody>