<?php
/** @var $block \Nexi\Checkout\Block\Info\Nexi */
/** @var $escaper \Magento\Framework\Escaper */
?>

<img src="<?= $escaper->escapeHtml($block->getNexiLogo() ? $block->getNexiLogo() : ''); ?>">
<p><?= $escaper->escapeHtml($block->getPaymentMethodTitle() ? $block->getPaymentMethodTitle() : '') ?></p>
<?= $block->getChildHtml()?>
<!--<p>Payment method: --><?php //= $block->escapeHtml($block->getPaymentSelectedMethod() ? $block->getPaymentSelectedMethod() : '()') ?><!--</p>-->
