<?php
/** @var $block \Nexi\Checkout\Block\Info\Nexi */
?>

<img src="<?= $block->escapeHtml($block->getNexiLogo() ? $block->getNexiLogo() : ''); ?>">
<p><?= $block->escapeHtml($block->getPaymentMethodTitle() ? $block->getPaymentMethodTitle() : '') ?></p>
<?= $block->getChildHtml()?>
<p>Payment method: <?= $block->escapeHtml($block->getPaymentSelectedMethod() ? $block->getPaymentSelectedMethod() : '()') ?></p>
