<?php
/** @var $block Nexi */
/** @var $escaper \Magento\Framework\Escaper */

use Nexi\Checkout\Block\Info\Nexi;

?>

<?= $block->getChildHtml() ?>
<table class="admin__table-secondary order-information-table">
    <tbody>
        <tr>
            <th><?= __('Payment Provider') ?></th>
            <td><img alt="Nexi Logo" style="width: 65px; height: 25px; background-color: white; "
                     src="<?= $escaper->escapeHtml($block->getLogo() ? $block->getLogo() : ''); ?>"/></td>
        </tr>
        <tr>
            <th><?= __('Payment Method') ?></th>
            <td><?= $escaper->escapeHtml($block->getSelectedPaymentMethodData()[Nexi::SELECTED_PATMENT_METHOD] ?? '') ?></td>
        </tr>
        <tr>
            <th><?= __('Payment Type') ?></th>
            <td><?= $escaper->escapeHtml($block->getSelectedPaymentMethodData()[Nexi::SELECTED_PATMENT_TYPE] ?? '') ?></td>
        </tr>
    </tbody>
</table>
<!--<p>Payment method: --><?php //= $block->escapeHtml($block->getPaymentSelectedMethod() ? $block->getPaymentSelectedMethod() : '()') ?><!--</p>-->
